feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
logging.level:
  com.qiang.feign.PaymentFeignClient: DEBUG
  ROOT: info
mybatis:
  mapper-locations: classpath:mapper/*
  configuration:
    mapUnderscoreToCamelCase: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#seata:
#  tx-service-group: my-tx-group
#  registry:
#    type: nacos
#    nacos:
#      application: seata-server
#      serverAddr: 127.0.0.1:8848
#      group: SEATA_GROUP
#      namespace: ""
#      cluster: default
#      username: nacos
#      password: nacos
#  service:
#    vgroup-mapping:
#      my-tx-group: default
